export const FETCH_PROPERTIES_START = 'FETCH_PROPERTIES_START';
export type FETCH_PROPERTIES_START = typeof FETCH_PROPERTIES_START;

export const FETCH_PROPERTIES_DONE = 'FETCH_PROPERTIES_DONE';
export type FETCH_PROPERTIES_DONE = typeof FETCH_PROPERTIES_DONE;

export const FETCH_PROPERTIES_ERROR = 'FETCH_PROPERTIES_ERROR';
export type FETCH_PROPERTIES_ERROR = typeof FETCH_PROPERTIES_ERROR;
